#!/bin/sh
#
# @name Generic Quadcopter
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#

# Swarobo_X650
. ${R}etc/init.d/rc.mc_defaults

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.15
param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.15
param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY -0.15
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY 0.15
param set-default CA_ROTOR3_KM -0.05

# Actuator
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default PWM_MAIN_DIS1 900
param set-default PWM_MAIN_DIS2 900
param set-default PWM_MAIN_DIS3 900
param set-default PWM_MAIN_DIS4 900
param set-default PWM_MAIN_MIN1 1100
param set-default PWM_MAIN_MIN2 1100
param set-default PWM_MAIN_MIN3 1100
param set-default PWM_MAIN_MIN4 1100

param set-default PWM_MAIN_MAX1 1950
param set-default PWM_MAIN_MAX2 1950
param set-default PWM_MAIN_MAX3 1950
param set-default PWM_MAIN_MAX4 1950

# MPC, MC parameters
param set-default MC_ROLLRATE_MAX 90
param set-default MC_PITCHRATE_MAX 90

param set-default MC_ROLLRATE_P 0.14
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_D 0.004
param set-default MC_ROLLRATE_K 1.0

param set-default MC_PITCHRATE_P 0.14
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_D 0.004
param set-default MC_PITCHRATE_K 1.0

param set-defulat MC_YAWRATE_MAX 150
param set-default MPC_XY_VEL_MAX 5.00

param set-default MPC_XY_P         0.95
param set-default MPC_XY_VEL_P_ACC 2.5
param set-default MPC_XY_VEL_I_ACC 0.4
param set-default MPC_XY_VEL_D_ACC 0.2

param set-default MPC_Z_VEL_P_ACC 4.5
param set-default MPC_Z_VEL_I_ACC 2.0
param set-default MPC_Z_VEL_D_ACC 0.0

param set-default MPC_Z_VEL_MAX_DN 3.00
param set-default MPC_Z_VEL_MAX_UP 3.00

param set-default MPC_LAND_ALT2 0.5
param set-default MPC_LAND_ALT1 3.0
param set-default MPC_LAND_SPEED 0.4
param set-default MPC_LAND_CRWL 0.3

param set-default COM_RCL_EXCEPT 4
param set-default COM_DL_LOSS_T 1200
param set-default NAV_RCL_ACT 3

# EKF2
param set-default EKF2_HGT_REF 1
param set-default EKF2_GPS_P_NOISE 0.2
param set-default EKF2_GPS_V_NOISE 0.2

# Mavlink
param set MAV_0_CONFIG 101

param set SER_TEL2_BAUD 115200
param set MAV_1_CONFIG 102
param set MAV_1_MODE 13                   # MAVLINK_MODE_LORARX
param set MAV_1_BROADCAST 0
param set MAV_1_FLOW_CTRL 2
param set MAV_1_RADIO_CTL 0

# UXRCE DDS
param set UXRCE_DDS_AG_IP 170461697
param set UXRCE_DDS_CFG 1000
param set UXRCE_DDS_PRT 8888

# Logging
param set SDLOG_MODE 1


monitoring start
